# Sampling
We will randomly select ~35 samples from original dataset. 
Using stratified sampling based on the test/test+repair attribute

In [1]:
import pandas as pd

In [2]:
stations = pd.read_csv("verified_avg_fee_by_station_jx.csv")

In [3]:
stations.head()

,No.,Station Id,Avg. Test Fees,Station Name,Address,City,ZIP,Phone Number,Price,Tax,On the Spot Registration,Registration/Sticker Fee,Service Type,Detailed Information
0,1.0,2.0,$25,KEN GARFF MERCEDES BENZ,575 SOUTH STATE,SALT LAKE CITY,84111.0,855-780-1053,25,0,Na,Na,TestAndRepair,Na
1,2.0,24.0,$39,OLYMPUS HILLS SINCLAIR,3905 SOUTH WASATCH BLVD,SALT LAKE CITY,84124.0,801- 272-2081,39,0,Na,Na,TestAndRepair,Na
2,3.0,28.0,$31,UNION SERVICE,997 EAST 7220 SOUTH,MIDVALE,84047.0,801-255-4122,Na,Na,Na,Na,Na,Na
3,4.0,38.0,$30,LARRY H. MILLER TOYOTA,5650 S STATE ST,MURRAY,84107.0,801-264-3850,30,0,Yes,5,TestAndRepair,Na
4,5.0,46.0,$35,QUALITY TIRE CO.,1335 WEST 2100 SOUTH,SALT LAKE CITY,84119.0,801-972-1944,Na,Na,Na,Na,Na,Na

In [4]:
stations['Service Type'] = stations['Service Type'].str.strip()

In [5]:
stations[['Station Id', 'Service Type']].groupby(['Service Type']).count()

                        Station Id
Service Type
Na                              55
Test+light repair                1
TestAndRepair                  337
TestAndRepair for ford           1
TestOnly                        30

In [6]:
stations.ix[stations['Service Type']=='Test+light repair', 'Service Type']='TestAndRepair'
stations.ix[stations['Service Type']=='TestAndRepair for ford', 'Service Type']='TestAndRepair'

/Users/xiaoguihua/anaconda3/envs/new_env/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
/Users/xiaoguihua/anaconda3/envs/new_env/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

In [7]:
stations[['Station Id', 'Service Type']].groupby(['Service Type']).count()

               Station Id
Service Type
Na                     55
TestAndRepair         339
TestOnly               30

## We will select 3 from 'test only' and 32 from 'test and repair'

In [8]:
test_only = stations.loc[stations['Service Type'] == 'TestOnly'].reset_index(drop=True)
test_and_repair = stations.loc[stations['Service Type'] == 'TestAndRepair'].reset_index(drop=True)

In [9]:
test_only.shape

(30, 14)

In [10]:
test_and_repair.shape

(339, 14)

In [11]:
to_s = test_only.sample(n=3, random_state = 2019)
tnr_s = test_and_repair.sample(n=32, random_state=2019)

In [12]:
sample = pd.concat([to_s, tnr_s], ignore_index=True)

In [13]:
sample.shape

(35, 14)

In [14]:
sample.to_csv('sample.csv')

## For supplimentary sample: we need 15 more: 1 from test only and 14 from test and repair

In [15]:
stations.head()

,No.,Station Id,Avg. Test Fees,Station Name,Address,City,ZIP,Phone Number,Price,Tax,On the Spot Registration,Registration/Sticker Fee,Service Type,Detailed Information
0,1.0,2.0,$25,KEN GARFF MERCEDES BENZ,575 SOUTH STATE,SALT LAKE CITY,84111.0,855-780-1053,25,0,Na,Na,TestAndRepair,Na
1,2.0,24.0,$39,OLYMPUS HILLS SINCLAIR,3905 SOUTH WASATCH BLVD,SALT LAKE CITY,84124.0,801- 272-2081,39,0,Na,Na,TestAndRepair,Na
2,3.0,28.0,$31,UNION SERVICE,997 EAST 7220 SOUTH,MIDVALE,84047.0,801-255-4122,Na,Na,Na,Na,Na,Na
3,4.0,38.0,$30,LARRY H. MILLER TOYOTA,5650 S STATE ST,MURRAY,84107.0,801-264-3850,30,0,Yes,5,TestAndRepair,Na
4,5.0,46.0,$35,QUALITY TIRE CO.,1335 WEST 2100 SOUTH,SALT LAKE CITY,84119.0,801-972-1944,Na,Na,Na,Na,Na,Na

In [16]:
index_ls = sample['No.']

In [17]:
#remove previous 
stations2 = stations[~stations['No.'].isin(index_ls)]

In [18]:
stations2.shape

(401, 14)

In [19]:
test_only2 = stations2.loc[stations2['Service Type'] == 'TestOnly'].reset_index(drop=True)
test_and_repair2 = stations2.loc[stations2['Service Type'] == 'TestAndRepair'].reset_index(drop=True)

In [20]:
to_s2 = test_only2.sample(n=1, random_state = 2019)
tnr_s2 = test_and_repair2.sample(n=14, random_state=2019)

In [21]:
sample2 = pd.concat([to_s2, tnr_s2], ignore_index=True)
sample2.to_csv('sample2.csv')

## Sadly, need 20 more
1 from test only, 19 from test and repair

In [22]:
#remove previous 
index_ls2 = sample2['No.']
stations3 = stations2[~stations2['No.'].isin(index_ls2)]
stations3.shape

(386, 14)

In [23]:
test_only3 = stations3.loc[stations3['Service Type'] == 'TestOnly'].reset_index(drop=True)
test_and_repair3 = stations3.loc[stations3['Service Type'] == 'TestAndRepair'].reset_index(drop=True)
to_s3 = test_only3.sample(n=1, random_state = 2019)
tnr_s3 = test_and_repair3.sample(n=19, random_state=2019)

In [24]:
sample3 = pd.concat([to_s3, tnr_s3], ignore_index=True)
sample3.to_csv('sample3.csv')

In [25]:
sample3

,No.,Station Id,Avg. Test Fees,Station Name,Address,City,ZIP,Phone Number,Price,Tax,On the Spot Registration,Registration/Sticker Fee,Service Type,Detailed Information
0,306.0,1442.0,$35,DEKRA SAFETY & EMISSIONS,7736 S STATE ST,MIDVALE,84047.0,801-255-6807,35,0,Na,Na,TestOnly,Na
1,302.0,1436.0,$37,MAIN STREET MUFFLER,3683 S MAIN ST,SALT LAKE CITY,84115.0,801-266-6565,35,0,Na,Na,TestAndRepair,Na
2,180.0,1189.0,$43,ALHERZ EMISSION AND REPAIR,4339 W 3500 S,WEST VALLEY CITY,84120.0,801-969-1417,35,0,Yes,5,TestAndRepair,Na
3,385.0,1559.0,$34,J & D AUTO REPAIR,634 W CENTER ST,MIDVALE,84047.0,801-808-9895,35,0,No,NaN,TestAndRepair,Na
4,268.0,1356.0,$31,RICHINS CAR SERVICE,568 E 12300 SO,DRAPER,84020.0,801-571-1111,31,0,Yes,Na,TestAndRepair,Na
5,89.0,904.0,$27,SANDY HIGH TECH AUTOMOTIVE,9217 SOUTH STATE,SANDY,84070.0,801-566-8171,26.5,0,Yes,6.5,TestAndRepair,Na
6,288.0,1405.0,$11,SINDY AUTO REPAIR,4690 S RIVERSIDE DR,MURRAY,84123.0,801-759-6540,20,0,No,Na,TestAndRepair,$5 credit card fee
7,287.0,1395.0,$44,FABULOUS FREDDYS CAR WASH,1065 E 9400 SO,SANDY,84094.0,801-523-2969,29.99,0,No,Na,TestAndRepair,Na
8,393.0,1569.0,$37,GREASE MONKEY,2928 S GLEN EAGLE DR,WEST VALLEY CITY,84128.0,801-969-0094,38,0,Yes,5,TestAndRepair,Na
9,382.0,1555.0,$20,ALLIANCE AUTO GROUP LLC,7291 S STATE ST UNIT 2,MIDVALE,84047.0,801-738-4444,24.95,0,Yes,10,TestAndRepair,Na
10,50.0,495.0,$35,JODY WILKINSON ACURA,1111 So. MAIN ST.,SALT LAKE CITY,84111.0,385- 202-7039,31,0,Yes,0,TestAndRepair,Na
11,9.0,70.0,$35,DENNYS AUTO,11999 SOUTH REDWOOD RD,RIVERTON,84065.0,801- 254-6554,35,0,No,Na,TestAndRepair,Na
12,58.0,574.0,$30,BT AUTOMOTIVE #574,7951 So. STATE ST,MIDVALE,84047.0,801-255-1340,30,0,Yes,0,TestAndRepair,Na
13,271.0,1362.0,$31,LARRY H MILLER USED CAR,10990 SO AUTOMALL DR,SANDY,84070.0,801-553-5300,30,0,No,Na,TestAndRepair,service rep said county gov sets $30 fee count...
14,395.0,1571.0,$39,D & V AUTO REPAIR INC,3495 S 8400 W,MAGNA,84044.0,801-250-5742,40,0,No,NaN,TestAndRepair,Na
15,232.0,1290.0,$15,CHUY'S MECHANIC SHOP,4711 SO 300 W,MURRAY,84107.0,801-706-6136,15,0,Yes,10,TestAndRepair,Na
16,379.0,1552.0,$28,EQUITY AUTO,2437 S 3270 W,WEST VALLEY CITY,84119.0,801-906-8486,40,0,Yes,10,TestAndRepair,Na
17,332.0,1487.0,$32,HAVOLINE XPRESS LUBE,4689 W 12600 SO,RIVERTON,84065.0,801-254-2013,30,0,Na,Na,TestAndRepair,Na
18,226.0,1280.0,$39,KEARNS BIG O TIRES,3725 W 5400 S,KEARNS,84118.0,801-964-9935,35,0,No,Na,TestAndRepair,Na
19,426.0,4011.0,$27,KENWORTH SALES CO. INC.,2125 CONSTITUTION BLVD,WEST VALLEY,84119.0,801-487-4161,29,0,No,NaN,TestAndRepair,Na

## Sadly, need another 20
1 from test only, 19 from test and repair

In [27]:
#remove previous 
index_ls3 = sample3['No.']
stations4 = stations3[~stations3['No.'].isin(index_ls3)]
stations4.shape

(366, 14)

In [28]:
test_only4 = stations4.loc[stations4['Service Type'] == 'TestOnly'].reset_index(drop=True)
test_and_repair4 = stations4.loc[stations4['Service Type'] == 'TestAndRepair'].reset_index(drop=True)
to_s4 = test_only4.sample(n=1, random_state = 2019)
tnr_s4 = test_and_repair4.sample(n=19, random_state=2019)

In [29]:
sample4 = pd.concat([to_s4, tnr_s4], ignore_index=True)
sample4.to_csv('sample4.csv')

In [30]:
sample4

,No.,Station Id,Avg. Test Fees,Station Name,Address,City,ZIP,Phone Number,Price,Tax,On the Spot Registration,Registration/Sticker Fee,Service Type,Detailed Information
0,308.0,1444.0,$34,DEKRA SAFETY & EMISSIONS,865 S STATE ST,SALT LAKE CITY,84111.0,801-433-5000,35,0,Na,Na,TestOnly,Na
1,59.0,580.0,$36,MARK MILLER SUBARU,3535 SO STATE ST,SALT LAKE CITY,84115.0,801-268-3734,35,0,Yes,11,TestAndRepair,Na
2,10.0,73.0,$37,THE LITTLE GARAGE,1161 SOUTH 300 WEST,SALT LAKE CITY,84101.0,801- 466-1161,40,0,No,Na,TestAndRepair,Na
3,398.0,1574.0,$42,BIG O TIRES,3557 S 5600 W,WEST VALLEY CITY,84120.0,801-967-6404,40,0,No,NaN,TestAndRepair,Na
4,76.0,805.0,$31,LARRY H. MILLER HONDA,5808 SOUTH STATE,MURRAY,84107.0,801-268-5599,30,0,No,Na,TestAndRepair,Na
5,128.0,1061.0,$30,BIG O TIRES,2830 W 3500 S,WEST VALLEY CITY,84119.0,801-967-7166,30,0,Yes,10,TestAndRepair,Na
6,54.0,537.0,$32,JEFFREY P. DAVIS AUTO,4707 SO COMMERCE DR,MURRAY,84107.0,801-263-2002,32,0,Yes,7,TestAndRepair,Na
7,102.0,981.0,$41,JIFFY LUBE NO.1147,1735 WEST 9000 SOUTH,WEST JORDAN,84088.0,801-566-4075,39,0,No,Na,TestAndRepair,less than 3hr labor
8,229.0,1285.0,$40,JIFFY LUBE No.14,1850 W 4100 SO,WEST VALLEY,84119.0,801-972-3455,39,0,Yes,10,TestAndRepair,Na
9,425.0,1601.0,$50,VALVOLINE INSTANT OIL,1065 E 9400 S,SANDY,84094.0,801-566-5188,50,0,No,NaN,TestAndRepair,Na
10,111.0,994.0,$38,JIFFY LUBE NO.2525,1625 W. 12600 So.,RIVERTON,84065.0,801-446-1315,39,0,Yes,10,TestAndRepair,coupons may apply
11,11.0,96.0,$27,NATE WADE SUBARU,1207 SOUTH MAIN ST.,SALT LAKE CITY,84111.0,888-654-7340,25,0,No,Na,TestAndRepair,Na
12,270.0,1361.0,$40,JEANNETTE AUTO REPAIR,4091 SO STATE ST BLDG B,SALT LAKE CITY,84107.0,801-262-2065,25,3,Yes,Na,TestAndRepair,Na
13,149.0,1109.0,$28,FIRESTONE TIRE & SERVICE,910 E. 6600 S.,MURRAY,84121.0,801-207-9496,27.5,0,Yes,10,TestAndRepair,Na
14,248.0,1320.0,$41,GOOD LOOKING DAVES INC,4580 S 300 W,MURRAY,84107.0,801-266-2229,40,0,No,Na,TestAndRepair,Na
15,394.0,1570.0,$35,LHM USED CAR SUPERMARKET,200 W 9000 S,SANDY,84070.0,801-553-5350,35,0,No,NaN,TestAndRepair,Na
16,278.0,1376.0,$37,EMISSION TIME,32 E 9000 S,SANDY,84070.0,801-948-4048,35,0,Yes,Na,TestAndRepair,Na
17,243.0,1313.0,$36,BIG O TIRE,8835 S 700 E,SANDY,84070.0,801-566-1177,35,0,Yes,10,TestAndRepair,Na
18,27.0,214.0,$28,THOMAS TIRE CENTER,3555 SOUTH 3600 WEST,WEST VALLEY CITY,84119.0,801-969-3555,25,0,Yes,10,TestAndRepair,Na
19,428.0,4014.0,$93,UNITED DIESEL SERVICE INC,1905 SO PIONEER RD,SALT LAKE CITY,84104.0,801-972-2378,93,0,No,NaN,TestAndRepair,Na